import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";

const Poppins_Font = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Poppins_Font.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
